version: '3'

tasks:

  build-debian:
    desc: Build kubectl (debian)
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - docker build . -f debian.Dockerfile -t bygui86/kubectl:{{.KUBECTL_VERSION}} --build-arg KUBECTL_VERSION={{.KUBECTL_VERSION}}

  build-alpine:
    desc: Build kubectl (alpine)
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - docker build . -f alpine.Dockerfile -t bygui86/kubectl:{{.KUBECTL_VERSION}}-alpine --build-arg KUBECTL_VERSION={{.KUBECTL_VERSION}}

  build-specific:
    desc: Build kubectl (all)
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - task: build-debian
        # INFO: env vars with same name are passed automatically
      - task: build-alpine

  build-latest:
    desc: Build kubectl (all)
    cmds:
      - task: build-debian
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)
      - task: build-alpine
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)

  push-debian:
    desc: Push kubectl (debian) to container registry
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - docker push bygui86/kubectl:{{.KUBECTL_VERSION}}

  push-alpine:
    desc: Push kubectl (alpine) to container registry
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - docker push bygui86/kubectl:{{.KUBECTL_VERSION}}-alpine

  push-specific:
    desc: Push kubectl (all) to container registry
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - task: push-debian
      - task: push-alpine

  push-latest:
    desc: Push kubectl (all) to container registry
    cmds:
      - task: push-debian
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)
      - task: push-alpine
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)

  build-push-specific:
    desc: Build kubectl (all) and push to container registry
    requires:
      vars: [ KUBECTL_VERSION ]
    cmds:
      - task: build-debian
      - task: push-debian
      - task: build-alpine
      - task: push-alpine

  build-push-latest:
    desc: Build kubectl (all) and push to container registry
    cmds:
      - task: build-debian
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)
      - task: push-debian
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)
      - task: build-alpine
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)
      - task: push-alpine
        vars:
          KUBECTL_VERSION: $(curl -L -s https://dl.k8s.io/release/stable.txt)
